### PR TITLE
enable travis and automatic snapshot publishing

### PR DESCRIPTION
**Pull request by lbergelson**
adding a trivial travis build that checks that the project compiles and then publishes snapshots
adding a travis badge to the README

### CODE REVIEW

**Comment by lbergelson** [comment]
@cmnbroad and here's a travis file to publish snapshots with automatically.  Don't merge it until we've checked that it's actually publishing them....

**Comment by cmnbroad** [comment]
This seems fine, and it looks like the snapshot got pushed [up](https://broadinstitute.jfrog.io/broadinstitute/webapp/#/artifacts/browse/tree/General/libs-snapshot-local/org/broadinstitute/gatk-native-bindings/0.0.5-1-g5c70987-SNAPSHOT), but for some reason the master build is failing at the moment. I'm restarting it.

**Comment by cmnbroad** [comment]
Hm, the master build fails repeatedly on travis - I'm guessing this is because there is no actual travis.yml in master yet. @lbergelson WDYT ?

**Comment by lbergelson** [comment]
@cmnbroad Yeah, master is failing because I enabled travis building without having a travis file there, so it just explodes.

**Comment by lbergelson** [comment]
There aren't any tests in this repo, so it's just a "compile or not" check.

**Pull request merged**
